version: "3.8"

services:
  vault-server:
    container_name: vault-server
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "confluent"
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
  vault-init:
    container_name: vault-init
    image: vault:latest
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    volumes:
      - ./run.sh:/opt/run.sh
    command: sh -c "/opt/run.sh"
