logging.level.root: INFO

application.topic.default.replicas: 1
application.topic.default.partitions: 1

application.topic.books: encrypted-payload-books
application.topic.orders: encrypted-payload-orders
application.topic.counts: encrypted-payload-counts

---
spring:
  config:
    activate:
      on-profile: local-encrypted-payload
  kafka:
    properties:
      bootstrap.servers: localhost:9092
      schema.registry.url: http://localhost:8081
    streams:
      application-id: encrypted-payload-avro-streams
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    producer:
      client-id: encrypted-payload-avro-producer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.encryption.serializers.avro.SecuredSpecificAvroSerializer
      properties:
        value.serializer.key: "DataCipher"
        encryption.provider.name: "generator"
        value.serializer.wrapping.key: "MasterCipher"
        value.serializer.wrapping.key.provider.name: "local"
        generator.provider.class: "AESGeneratorCipherProvider"
        generator.provider.symmetric.key.size: 256
        local.provider.class: "LocalCipherProvider"
        local.provider.keys: "MasterCipher"
        local.provider.MasterCipher.key.type: "KeyPair"
        local.provider.MasterCipher.key.private: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDnaSw7eWcppqCW0dMJ9Q1aC+aUvg7K0xTYfEStyMOym9a+EKjcr/6hU0LkIUksmSmLGBgYVAey2OPXFmO1B3Qbvxla9EPtdQ/qilJluB7HH2z10oeBuS7tkdo+zA/u4AHDOCfa9+yk47IWNLPBjkVs4xMo3cL6rVyM5hu5hVq3lRVYbVV2AT7oYdM3C6nEw5kdE01uSgjkcpd7Rg58ZiLNYdr91rwEblxxoF40tdHBs5oQ4DWMyx1hZ1npyekEsVYsq/ACsEaIMGQXNZsLZ7XXmAV14sZXvSVsHiUGkv/7LKgsUEZ0lUH9PRqs4jK+6nSQOxiLqM6yCRAzr5MSiOlXAgMBAAECggEAKC3fqzfqDJZM3cLyxJDSz6avU3YodVjvDqOM/SuVpwZd48RavW6lZHdjbt7EqMSzLN5zGI5Gg+waqzbM+xqfM04b5enxfWJM8CkyI00zstkm/wud0Y1Is6EWZr7hqVUlmTK/4MoZQYvzWN2vtFSygzRuGDNg7kt5fVFa0PxxgtxAPwOXFWDMT7bU7csjrsOtxm7bgwm+rxSCSPU9J834TTzQlPID8tP9Ajvj4TrllZN55oKdDNO5aVaMkYRKMBbg/mzHpQE9wWeKX1iGYR0x8N3ctKJvAC6SYcnOiAKKPg0C5Qi6RFg88GdaYq1tUtDbjcP5CUWMZ2X9M5XEqO2WAQKBgQD3iRy7Fm91EFy2duJxNULe0qU5hbRekCmEX7/5HNk+BjWDFLLVFkgtWop7+p+G/TwmmPdpEtRYCbT1k2qHrPgohReo2VzF+K7Q3yppnFu2dPy5T2AL02J9J4BCzxB1uwzpnGd2PqwUX79WsF2ol18F04sMeXUzuKggOm7M2nl8VwKBgQDvUugqw3Yfl9TF5VkVyA26/FOfMYQZ2ovzpTg9Qq7il1F37h8Lg83zvI63NXUlY2khweo0FyMbtZpG0a9dpQBE0f4D2n9JsmpuGbgjYYNNEWUQvuI3bqdQ/ecPpMGvYXWvtnTPG0jr6GbSobL/RXwgOp4H8tOpFNEejaARjDfbAQKBgQCmpYdTKMqGnCpeqPDP2FSZoGSdsjb5BsL8nF2ov1Q93n4+LjwrGuIirnbW+qZVgbzyGz9NXODaGEbcoY8xojA7T0bbZOKBYWeHtQZfrWVNE7tkolx9+aSvr105HR/usqwBxksdHxpIaSFuojObobTWPlG5ZzeRR3rgn5Yikd8B5wKBgQC2+GLJ9wBDbTheSFdQoM9miu1/w0Kk5YKkN0gFBgtg76F4mJQhoJZ/50QRbAxxFkzVY0UkqB/OWoxl4oA5jyHie83BsnYoqQBXxtASNMZG0Kq9H8Mh8DZ5ZHUYb7Uo2dE5ErzBbrHUsqySEtAf/EbG+SnDF/KczW6H9m1PnS1DAQKBgCANQP+nXYE2/81+wmlPqOZqpXdZaTc8tNB2vHfpamw/OCZqoRmZB9iUPOVfeTH6JmlL3K1BRaDnYJci/rWP/QjGLcterlihnZvOzVOfBgsS8MXw1jUjThNI6YAzhEOKBantke/ngwC+3X0s7GoEUIP+D3zdGAk34RhvEryeF+dY"
        local.provider.MasterCipher.key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA52ksO3lnKaagltHTCfUNWgvmlL4OytMU2HxErcjDspvWvhCo3K/+oVNC5CFJLJkpixgYGFQHstjj1xZjtQd0G78ZWvRD7XUP6opSZbgexx9s9dKHgbku7ZHaPswP7uABwzgn2vfspOOyFjSzwY5FbOMTKN3C+q1cjOYbuYVat5UVWG1VdgE+6GHTNwupxMOZHRNNbkoI5HKXe0YOfGYizWHa/da8BG5ccaBeNLXRwbOaEOA1jMsdYWdZ6cnpBLFWLKvwArBGiDBkFzWbC2e115gFdeLGV70lbB4lBpL/+yyoLFBGdJVB/T0arOIyvup0kDsYi6jOsgkQM6+TEojpVwIDAQAB"
    consumer:
      group-id: encrypted-payload-avro-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.encryption.serializers.avro.SecuredSpecificAvroDeserializer
      properties.specific.avro.reader: true
      auto-offset-reset: latest
      properties:
        value.deserializer.key: "DataCipher"
        encryption.provider.name: "generator"
        value.deserializer.wrapping.key: "MasterCipher"
        value.deserializer.wrapping.key.provider.name: "local"
        generator.provider.class: "AESGeneratorCipherProvider"
        generator.provider.symmetric.key.size: 256
        local.provider.class: "LocalCipherProvider"
        local.provider.keys: "MasterCipher"
        local.provider.MasterCipher.key.type: "KeyPair"
        local.provider.MasterCipher.key.private: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDnaSw7eWcppqCW0dMJ9Q1aC+aUvg7K0xTYfEStyMOym9a+EKjcr/6hU0LkIUksmSmLGBgYVAey2OPXFmO1B3Qbvxla9EPtdQ/qilJluB7HH2z10oeBuS7tkdo+zA/u4AHDOCfa9+yk47IWNLPBjkVs4xMo3cL6rVyM5hu5hVq3lRVYbVV2AT7oYdM3C6nEw5kdE01uSgjkcpd7Rg58ZiLNYdr91rwEblxxoF40tdHBs5oQ4DWMyx1hZ1npyekEsVYsq/ACsEaIMGQXNZsLZ7XXmAV14sZXvSVsHiUGkv/7LKgsUEZ0lUH9PRqs4jK+6nSQOxiLqM6yCRAzr5MSiOlXAgMBAAECggEAKC3fqzfqDJZM3cLyxJDSz6avU3YodVjvDqOM/SuVpwZd48RavW6lZHdjbt7EqMSzLN5zGI5Gg+waqzbM+xqfM04b5enxfWJM8CkyI00zstkm/wud0Y1Is6EWZr7hqVUlmTK/4MoZQYvzWN2vtFSygzRuGDNg7kt5fVFa0PxxgtxAPwOXFWDMT7bU7csjrsOtxm7bgwm+rxSCSPU9J834TTzQlPID8tP9Ajvj4TrllZN55oKdDNO5aVaMkYRKMBbg/mzHpQE9wWeKX1iGYR0x8N3ctKJvAC6SYcnOiAKKPg0C5Qi6RFg88GdaYq1tUtDbjcP5CUWMZ2X9M5XEqO2WAQKBgQD3iRy7Fm91EFy2duJxNULe0qU5hbRekCmEX7/5HNk+BjWDFLLVFkgtWop7+p+G/TwmmPdpEtRYCbT1k2qHrPgohReo2VzF+K7Q3yppnFu2dPy5T2AL02J9J4BCzxB1uwzpnGd2PqwUX79WsF2ol18F04sMeXUzuKggOm7M2nl8VwKBgQDvUugqw3Yfl9TF5VkVyA26/FOfMYQZ2ovzpTg9Qq7il1F37h8Lg83zvI63NXUlY2khweo0FyMbtZpG0a9dpQBE0f4D2n9JsmpuGbgjYYNNEWUQvuI3bqdQ/ecPpMGvYXWvtnTPG0jr6GbSobL/RXwgOp4H8tOpFNEejaARjDfbAQKBgQCmpYdTKMqGnCpeqPDP2FSZoGSdsjb5BsL8nF2ov1Q93n4+LjwrGuIirnbW+qZVgbzyGz9NXODaGEbcoY8xojA7T0bbZOKBYWeHtQZfrWVNE7tkolx9+aSvr105HR/usqwBxksdHxpIaSFuojObobTWPlG5ZzeRR3rgn5Yikd8B5wKBgQC2+GLJ9wBDbTheSFdQoM9miu1/w0Kk5YKkN0gFBgtg76F4mJQhoJZ/50QRbAxxFkzVY0UkqB/OWoxl4oA5jyHie83BsnYoqQBXxtASNMZG0Kq9H8Mh8DZ5ZHUYb7Uo2dE5ErzBbrHUsqySEtAf/EbG+SnDF/KczW6H9m1PnS1DAQKBgCANQP+nXYE2/81+wmlPqOZqpXdZaTc8tNB2vHfpamw/OCZqoRmZB9iUPOVfeTH6JmlL3K1BRaDnYJci/rWP/QjGLcterlihnZvOzVOfBgsS8MXw1jUjThNI6YAzhEOKBantke/ngwC+3X0s7GoEUIP+D3zdGAk34RhvEryeF+dY"
        local.provider.MasterCipher.key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA52ksO3lnKaagltHTCfUNWgvmlL4OytMU2HxErcjDspvWvhCo3K/+oVNC5CFJLJkpixgYGFQHstjj1xZjtQd0G78ZWvRD7XUP6opSZbgexx9s9dKHgbku7ZHaPswP7uABwzgn2vfspOOyFjSzwY5FbOMTKN3C+q1cjOYbuYVat5UVWG1VdgE+6GHTNwupxMOZHRNNbkoI5HKXe0YOfGYizWHa/da8BG5ccaBeNLXRwbOaEOA1jMsdYWdZ6cnpBLFWLKvwArBGiDBkFzWbC2e115gFdeLGV70lbB4lBpL/+yyoLFBGdJVB/T0arOIyvup0kDsYi6jOsgkQM6+TEojpVwIDAQAB"
