version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: confluent

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    hostname: mongodb-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: confluent
      ME_CONFIG_MONGODB_URL: mongodb://root:confluent@mongodb:27017/