# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: confluent

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "18081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: confluent
      ME_CONFIG_MONGODB_URL: mongodb://root:confluent@mongo:27017/